In [1]:
# 1. TF 1.0和TF 2.0的区别
# Tensorflow 2.0 supports eager execution by default. It allows you to build your models and 
# run them instantly

# 2. Tensorflow 2.0 内置Keras API
# Sequential - 顺序模型， 一层叠下一层
# Functional - 一个层分层两个层，然后两个层又叠层一层这种奇葩操作，一般在分类模型中使用
# Subclassing - 复杂模型，继承Model类，自己实现自己的模型
# 详情可以查看北大 Tensorflow教程曹健教授的课程

In [3]:
# Keras is the high level API in Tensorflow 2.0
# 3. Tensorflow 2.0 不需要tf.variable块了

In [4]:
# 4. API Cleanup
# In Tensorflow 2.0, a lot of APIs have been removed such as tf.app, tf.flags, and tf.logging

In [6]:
# 5. Tensorflow 2.0 加入tf.function和AutoGraph特性

In [8]:
# 6. 回忆下数据流图是个啥
# Tensorflow performs computations with the help of dataflow graphs.
# It has nodes that represent the operations in your model

In [10]:
# 7. Tensorflow Toolkits Hierarchy
# Estimator, tf.keras ----- High Level, object-oriented API
# tf.layers, tf.losses, tf.metrics ----- Reusable libraries for model building
# low-level TF API ----- Extensive control
# CPU, GPU, TPU ----- TF code can run on multiple platforms

In [11]:
# 8. Tensorflow 2.0 Architecture

# Read & Preprocess data 
# Tensorflow Hub --> tf.keras, Premade estimators
# Distribution strategy --> CPU, GPU, TPU

# Saved model deployed --> Tensorflow serving cloud, on-prem
#                          Tensorflow lite, Android, iOS, Raspberry PI
#                          Tensorflow.js, Browser and Node server
#                          Other language bindings, C, Java, Go, C#, Rust, R...

In [12]:
# 看下tf的版本
import tensorflow as tf
print(tf.__version__)

2.5.1


In [14]:
# 我们的版本会新一点
# tf.constant创建常量
# tf.Variable创建变量
# tf.concat 合并变量

A = tf.constant([[4,3], [6,1]], dtype=tf.int32)
B = tf.constant([[7,8], [4,5]], dtype=tf.int32)

AB_concatenated = tf.concat(values=[A, B], axis=1)
AB_concatenated

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 3, 7, 8],
       [6, 1, 4, 5]], dtype=int32)>

In [15]:
# tf.concat axis =0 就可以按row concat
AB_concatenated = tf.concat(values=[A, B], axis=0)
AB_concatenated

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[4, 3],
       [6, 1],
       [7, 8],
       [4, 5]], dtype=int32)>

In [17]:
# 各个平台上的float位数不同，我们需要 take care of it。
# Tensorflow提供了各个平台上的不同数据类型的长度，便于移植

tf.zeros((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [18]:
# 我们可以指定zeros的类型

tensor = tf.zeros((3, 4), dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [20]:
# tf.ones
ones = tf.ones((3, 4), dtype=tf.float32)
ones

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [21]:
# tf.reshape
reshaped_ones = tf.reshape(tensor=ones, shape=[4, 3])
reshaped_ones

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [22]:
# tf.random.uniform
# 3*4 均匀分布的随机数

tensor = tf.random.uniform(shape=[3, 4], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.36536753, 0.33566654, 0.24723816, 0.12452435],
       [0.16359544, 0.034729  , 0.39126766, 0.70757914],
       [0.71276   , 0.2448641 , 0.9439751 , 0.25460708]], dtype=float32)>

In [23]:
# tf.cast
# int32之后，小数位全部被去掉了

tensor = tf.constant([[4.6, 4.2],
                     [7.5, 3.6],
                     [2.7, 9.4],
                     [6.7, 8.3]],
                    dtype=tf.float32)

tensor_as_int = tf.cast(tensor, tf.int32)
print(tensor)
print(tensor_as_int)

tf.Tensor(
[[4.6 4.2]
 [7.5 3.6]
 [2.7 9.4]
 [6.7 8.3]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[4 4]
 [7 3]
 [2 9]
 [6 8]], shape=(4, 2), dtype=int32)


In [24]:
# 转置

a = tf.transpose(tensor_as_int)
a

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[4, 7, 2, 6],
       [4, 3, 9, 8]], dtype=int32)>

In [25]:
# 矩阵乘法
a = tf.constant([[5, 8],
                [3, 9]])

b = tf.constant([[4],
                [2]])

ab = tf.matmul(a, b)
ab

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[36],
       [30]], dtype=int32)>

In [26]:
# 乘法
# 按行做乘法
# Element-wise multiplication
a_b_mul = tf.multiply(a, b)
a_b_mul


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 32],
       [ 6, 18]], dtype=int32)>

In [28]:
# shape
A = tf.constant([[4, 9], 
                [5, 6],
                [1, 8]])

rows, cols = A.shape
print('rows: ', rows, 'columns: ', cols)

rows:  3 columns:  2


In [29]:
# 构建单位阵
a_identity = tf.eye(num_rows=rows,
                   num_columns=cols,
                   dtype=tf.int32)

a_identity

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1],
       [0, 0]], dtype=int32)>