In [5]:
# 1. constants
# Constants are parameters whose value dose not change. To define a constant we use tf.constant() command

import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.constant(2.0, tf.float32)
b = tf.constant(3.0)
print(a, b)

Instructions for updating:
non-resource variables are not supported in the long term
Tensor("Const:0", shape=(), dtype=float32) Tensor("Const_1:0", shape=(), dtype=float32)


In [13]:
# 2. Variables
# Variables allow us to add new trainable parameters to graph. To define a variable, we use tf.Variable()
# command and initialize them before running the graph in a session

W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)
linear_model = W*x + b
init_op = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    result = sess.run(linear_model, feed_dict={x: [2.0, 3.0, 4.0]})
    print(result)

[0.3        0.6        0.90000004]


In [14]:
# 3. placeholders
# placeholder用于从外部获取数据。
# 因为一次放入所有数据可能内存或显存不允许，所以要分批放，
# 就出现了placeholder

a = tf.placeholder(tf.float32)
b = a*2
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    result = sess.run(b, feed_dict={a: 3.0})
    print(result)

6.0


In [15]:
# 4. session 是用来运行计算图的
# A session is run to evaluate the nodes. This is called as the Tensorflow runtime

a = tf.constant(5.0)
b = tf.constant(3.0)
c = a*b
sess = tf.Session()
print(sess.run(c))
sess.close()


15.0


In [20]:
# Variables in tensorflow

my_tensor = tf.random_uniform((4, 4), 0, 1)
my_var = tf.Variable(initial_value=my_tensor)
print(my_var)

init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    result = sess.run(my_var)
    print(result)

<tf.Variable 'Variable_20:0' shape=(4, 4) dtype=float32_ref>
[[0.02030647 0.76771295 0.49416745 0.32624507]
 [0.92596006 0.5082898  0.98873127 0.9755006 ]
 [0.32086253 0.35333228 0.7082212  0.90127647]
 [0.98199797 0.21985614 0.09453106 0.6298727 ]]


In [21]:
# Constant Example
hello = tf.constant("Hello")

print(type(hello))

<class 'tensorflow.python.framework.ops.Tensor'>


In [24]:
world = tf.constant("World")
result = hello + world
print(result)
print(type(result))

Tensor("add_10:0", shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.Tensor'>


In [25]:
with tf.Session() as sess:
    result = sess.run(hello + world)
    print(result)

b'HelloWorld'


In [29]:
# placeholder
# It's common to use (None, # of features) for shape as none can be filled by number of samples in the data
ph = tf.placeholder(tf.float32, shape=(None, 5))
b = ph * 2
with tf.Session() as sess:
    result = sess.run(b, feed_dict={ph: [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]})
    print(result)

[[ 2.  4.  6.  8. 10.]
 [12. 14. 16. 18. 20.]]


In [32]:
# Constant

tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)
print(type(tensor_1))
with tf.Session() as sess:
    result = sess.run(tensor_1 + tensor_2)
    print(type(result))
    print(result)

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'numpy.int32'>
3


In [36]:
# 矩阵乘法

a = tf.constant([[1, 2], 
                 [3, 4]])

print(a.get_shape())

b = tf.constant([[10], [100]])
print(b.get_shape())

mul = tf.matmul(a, b)
with tf.Session() as sess:
    result = sess.run(mul)
    print(result)

(2, 2)
(2, 1)
[[210]
 [430]]


In [37]:
# 创建额外的Graph

n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1 + n2
with tf.Session() as sess:
    result = sess.run(n3)
    print(result)

3


In [39]:
# When you start TF, a default graph is created. You can create additional graphs easily
print(tf.get_default_graph())
g = tf.Graph()
print(g)

In [68]:
# Actual Code

zero = tf.Variable(0)
one = tf.constant(1)
new_value = tf.add(zero, one)
# Variable value can be changed
update = tf.assign(zero, new_value)
print(zero)
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    for i in range(5):
        sess.run(update)
        result2 = sess.run(zero)
        print(result2)

<tf.Variable 'Variable_46:0' shape=() dtype=int32_ref>
1
2
3
4
5


In [63]:
# 尝试改变常量的值
# update_const = tf.assign(one, new_value)

# 如果有变量的话， 必须先初始化 global_variables,才能往后面跑，否则会翻车

In [69]:
# string 操作

hello = tf.constant('hello')
world = tf.constant('world')
helloworld = tf.add(hello, world)

with tf.Session() as sess:
    result = sess.run(helloworld)
    print(result)

b'helloworld'


In [70]:
# placeholder
a = tf.placeholder(tf.float32)

b = a*2

sess = tf.Session()
result = sess.run(b, feed_dict={a: 3})
sess.close()
print(result)

6.0


In [71]:
# placeholders不加feed_dict这个名字也可以
sess = tf.Session()
result = sess.run(b, {a: 3})
sess.close()
print(result)

6.0


In [72]:
# feed一个vector也可以
sess = tf.Session()
result = sess.run(b, feed_dict={a: [3, 4, 5]})
sess.close()
print(result)

[ 6.  8. 10.]


In [74]:
# feed一个多维matrix
# 2 * 4 * 3

sess = tf.Session()
dictionary = {a: [[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18], [19, 20, 21], [22, 23, 24]]]}
result = sess.run(b, feed_dict=dictionary)
sess.close()
print(result)


[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [75]:
# 7. Graph 如何工作
# 单一的节点在Tensorflow的图中也叫操作

graph = tf.get_default_graph()
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf.Operation 'Variable_2/read' type=Identity>,
 <tf.Operation 'Variable_3/initial_value' type=Const>,
 <tf.Operation 'Variable_3' type=VariableV2>,
 <tf.Operation 'Variable_3/Assign' type=Assign>,
 <tf.Operation 'Variable_3/read' type=Identity>,
 <tf.Operation 'Placehol

In [76]:
# 给constant 取名的两种情况，第一种就是在计算图里面打印，就像现在
# 第二种就是在 tensorboard里面看，
# 其他情况其实加不加name没什么意义

a = tf.constant(10, name='a')
operations = graph.get_operations()
operations

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf.Operation 'Variable_2/read' type=Identity>,
 <tf.Operation 'Variable_3/initial_value' type=Const>,
 <tf.Operation 'Variable_3' type=VariableV2>,
 <tf.Operation 'Variable_3/Assign' type=Assign>,
 <tf.Operation 'Variable_3/read' type=Identity>,
 <tf.Operation 'Placehol

In [80]:
b = tf.constant(20, name='b')
operations = graph.get_operations()
operations[-5:]

[<tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'b_1' type=Const>,
 <tf.Operation 'b_2' type=Const>,
 <tf.Operation 'b_3' type=Const>]

In [81]:
# 这会还没加，只是构建图，所以是0

c = tf.add(a, b, name='c')
c

<tf.Tensor 'c:0' shape=() dtype=int32>

In [83]:
operations = graph.get_operations()
operations[-10:]

[<tf.Operation 'Add_40' type=Add>,
 <tf.Operation 'Placeholder_13' type=Placeholder>,
 <tf.Operation 'mul_14/y' type=Const>,
 <tf.Operation 'mul_14' type=Mul>,
 <tf.Operation 'a' type=Const>,
 <tf.Operation 'b' type=Const>,
 <tf.Operation 'b_1' type=Const>,
 <tf.Operation 'b_2' type=Const>,
 <tf.Operation 'b_3' type=Const>,
 <tf.Operation 'c' type=Add>]

In [84]:
d = tf.multiply(a, b, name='d')
d

<tf.Tensor 'd:0' shape=() dtype=int32>

In [85]:
e = tf.multiply(c, d, name='e')
e

<tf.Tensor 'e:0' shape=() dtype=int32>

In [89]:
sess = tf.Session()
result = sess.run(e)
# 打印操作列表名
for op in graph.get_operations():
    print(op.name)

sess.close()

print(result)

Const
Const_1
Variable/initial_value
Variable
Variable/Assign
Variable/read
Variable_1/initial_value
Variable_1
Variable_1/Assign
Variable_1/read
Placeholder
mul
add
Variable_2/initial_value
Variable_2
Variable_2/Assign
Variable_2/read
Variable_3/initial_value
Variable_3
Variable_3/Assign
Variable_3/read
Placeholder_1
mul_1
add_1
Variable_4/initial_value
Variable_4
Variable_4/Assign
Variable_4/read
Variable_5/initial_value
Variable_5
Variable_5/Assign
Variable_5/read
Placeholder_2
mul_2
add_2
Variable_6/initial_value
Variable_6
Variable_6/Assign
Variable_6/read
Variable_7/initial_value
Variable_7
Variable_7/Assign
Variable_7/read
Placeholder_3
mul_3
add_3
Variable_8/initial_value
Variable_8
Variable_8/Assign
Variable_8/read
Variable_9/initial_value
Variable_9
Variable_9/Assign
Variable_9/read
Placeholder_4
mul_4
add_4
init
Variable_10/initial_value
Variable_10
Variable_10/Assign
Variable_10/read
Variable_11/initial_value
Variable_11
Variable_11/Assign
Variable_11/read
Placeholder_5
mul