In [2]:
# 1. What is numpy
# Numpy is the core library for scientific and numeric computing in Python
# It provides high-performance multidemensional array object and tools for working with arrays

# Numpy's main object is the multidemensional array
# It is a table of elements (usually numbers), all of the same type, indexed by a tuple of postitive integers.
# In numpy, dimensions are called axes

In [3]:
# 2. 一维数组举例
# One-dimensional array
# 0, 1, 2, 3, 4, 5
# shape(6, )

In [5]:
# 3. 二维数组
# 0, 1, 2, 3
# 4, 5, 6, 7
# shape(2, 4)

In [6]:
# 6.Code
# 打印Hello World

print('hello world')

hello world


In [7]:
# 打印最后一行的变量
a = 'hello world'
a

'hello world'

In [8]:
# 7. NumyArray和Python list对比
# Why we should use numpy array when we have python lists?
# Fast/Convenient/Less Memory

In [9]:
# 8. Code
# import numpy ，构建一个array并打印他

import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [10]:
# 也可以用a[0], a[1] 来索引他
a[0]

1

In [11]:
a[1]

2

In [12]:
# 9. 比较numpy的好处
# numpy array占用空间少

import time
import sys

In [13]:
b = range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [20]:
c = np.arange(1000)
print(c.size * c.itemsize)

8000


In [23]:
# python list计算两个array相加，比较慢
size = 100000
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

result = [(x+y) for x,y in zip(L1, L2)]
start = time.time()
result = [(x+y) for x,y in zip(L1, L2)]
print('Python list took: ', (time.time() - start) * 1000)

Python list took:  13.947486877441406


In [24]:
# numpy array相加，计算比较快
result = A1 + A2
start = time.time()
result = A1 + A2
print('Numpy array took: ', (time.time() - start) * 1000)

Numpy array took:  0.4687309265136719


In [26]:
# 10. 二维数组构建
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# 维数
a.ndim

2

In [28]:
# 单个元素大小
a.itemsize

8

In [29]:
# shape
a.shape

(3, 2)

In [30]:
# 11. 构建一个浮点array
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [31]:
# 浮点数的itemsize 是 8
a.itemsize

8

In [32]:
a.shape

(3, 2)

In [44]:
# 12. 构建一个complex【复数】array
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.complex64)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]], dtype=complex64)

In [49]:
# Google查一下，可以找到所有基础数据类型
# https://numpy.org/doc/stable/user/basics.types.html