In [1]:
# 构建两个一行两列的矩阵
import numpy as np
a = np.array([[10, 15]])
b = np.array([[20, 9]])
print(a)
print(b)
print()

[[10 15]]
[[20  9]]



In [2]:
# 2. 矩阵加法

a + b

array([[30, 24]])

In [3]:
# 3. 转秩相加也可以

print(a.T)
print(b.T)

print(a.T + b.T)

[[10]
 [15]]
[[20]
 [ 9]]
[[30]
 [24]]


In [4]:
# 4. a+b再转秩也可以

print((a+b).T)

[[30]
 [24]]


In [5]:
# 5. 矩阵减法
print(a - b)

[[-10   6]]


In [6]:
# 转秩亦可
print((a - b).T)

[[-10]
 [  6]]


In [7]:
# 6. 标量相乘，会做广播
a = 2
u = np.array([[30, 15]])
a * u

array([[60, 30]])

In [8]:
# 转秩亦可

(a * u).T

array([[60],
       [30]])

In [9]:
# 7. 2D向量，np.dot就是矩阵乘法
u = np.array([10, 20])
v = np.array([25, 6])
print(10 * 25 + 20* 6)
print(np.dot(u, v))

370
370


In [10]:
# 8. 两个 3*2的矩阵，打印下a,b

a = np.array([[12, 10], [4, 6], [40, 31]])
b = np.array([[2, 8], [46, 63], [50, 10]])

print(a, end=' = a\n\n')
print(b, end=' = b\n\n')

[[12 10]
 [ 4  6]
 [40 31]] = a

[[ 2  8]
 [46 63]
 [50 10]] = b



In [11]:
# 矩阵加法
a + b

array([[14, 18],
       [50, 69],
       [90, 41]])

In [12]:
# 9. 矩阵减法
a - b

array([[ 10,   2],
       [-42, -57],
       [-10,  21]])

In [13]:
# 10. 矩阵标量乘法

a = 4
b = np.array([[2, 5], [3, 7], [8, 6]])
a * b

array([[ 8, 20],
       [12, 28],
       [32, 24]])

In [14]:
# 11. 矩阵和向量相乘

a = [[5, 10], [15, 20]]
b = [10, 12]

np.dot(a, b)

array([170, 390])

In [16]:
# 12. 矩阵和矩阵相乘

a = np.array([[5, 10], [15, 20], [25, 30]])
b = np.array([[3, 6], [9, 5]])
print(a)
print(b)
np.dot(a, b)

[[ 5 10]
 [15 20]
 [25 30]]
[[3 6]
 [9 5]]


array([[105,  80],
       [225, 190],
       [345, 300]])

In [17]:
# 13. 矩阵转秩

a = np.array([[5, 10], [15, 20], [25, 30]])
print(a, end=' = a \n\n')
print(a.T, end=' = a.T \n\n')

[[ 5 10]
 [15 20]
 [25 30]] = a 

[[ 5 15 25]
 [10 20 30]] = a.T 



In [18]:
# 14. 创建单位阵

i1 = np.eye(2)
i2 = np.eye(3)

print(i1, end=' = i1\n\n')
print(i2, end=' = i2\n\n')

[[1. 0.]
 [0. 1.]] = i1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] = i2



In [19]:
# 15. 求逆矩阵
# 逆矩阵的含义
# 一个方阵A
# A* Ainv = Ainv * A = I

a = np.array([
    [2, 1, 0],
    [0, 1, 0],
    [1, 2, 1]
])

print(a, end = ' = a\n\n')
print(np.linalg.inv(a), end = ' = inv(a)')

[[2 1 0]
 [0 1 0]
 [1 2 1]] = a

[[ 0.5 -0.5  0. ]
 [ 0.   1.   0. ]
 [-0.5 -1.5  1. ]] = inv(a)